### ISSUE TITLE
Mature open-source alternative

### ISSUE THREAD

**Issue by lwouis** [numist/Switch#136]
Hi!

I found this project today by accident. It's great to see someone else wanting to bring `alt-tab` to the mac. I have been working for a while now on basically the same project. It's [over there](https://alt-tab-macos.netlify.app/).

I thought you may be interested in either taking inspiration from the project, its UI, UX, or implementation details, or potentially even stop effort here and join the other project.

I want to be sure that you don't get my message the wrong way: I'm in no way being negative towards this project. I just thought that you may not be aware that my project exists and is quite popular. From there, of course it's up to you to decide what to do next. I don't want to sound rude at all! I'm actually going to study the code in this project to see if there are techniques/ideas I missed in mine 👍 

Warm regards,

Louis Pontoise

**Comment by therontarigo** [comment]
Hi Louis,

Will you consider releasing "AltTab" under a license such as MIT or similar?  I've been moving away from dependence on GNU-licensed utilities and was happy to find that "Switch" was exactly what I was looking for.

**Comment by lwouis** [comment]
Hi @therontarigo!

I was greatly inspired by the story behind VLC and how the fellow Frenchman behind the project refused millions of dollars to get toolbars and other malware packaged with VLC as it represents almost 1 billion installs worldwide.

I picked the GPL3 license in that spirit, and don't plan on changing at the moment. The license does inspire me to work on the project!

**Comment by therontarigo** [comment]
It's great to see free software authors stand up for the integrity of their project and for the safety of their users, and this has happened across communities with differing approaches to licensing.  It is very disappointing when "open-source" brands, some built on much GPL software, sell out and bundle crapware (and GPL turns out to be not much of an effective legal mechanism against this).

Many developers take inspiration from the tenets of free software more generally, and some dedicated free software authors have found good reason for concern about the GNU licensing approach.

But I didn't come here to have a GPL argument, and your enthusiasm for your tool is also inspiring.  Have a nice day!

**Comment by lwouis** [comment]
> some dedicated free software authors have found good reason for concern about the GNU licensing approach

Could you please share some links explaining these concerns? I'm interested in learning about these. I'm open-minded about lots of things, and If I discover things I wasn't aware of, I can always change my mind of course

> I didn't come here to have a GPL argument

No worries! I'm enjoying critical discourse. It's a great way to confront perspectives and learn in the process

**Comment by numist** [comment]
> I thought you may be interested in either taking inspiration from the project, its UI, UX, or implementation details, or potentially even stop effort here and join the other project.

Thanks for letting me know of its existence, I'll definitely take a look!

Joining the efforts of more open source projects is not especially compatible with the terms of my employment at the moment¹, but mostly I just enjoy having this little project around as a playground for playing with ideas 😄 

Closing, as this is not an actual issue.

----
¹: Which is ironic given that my primary responsibility is maintaining a popular open source database engine
