### ISSUE TITLE
Build fails if developer doesn't have "Mac Developer" codesigning identity

### ISSUE THREAD

**Issue by vanrijn** [numist/Switch#26]
I tried building with Xcode5 and hit this:

> Check dependencies
> 
> Code Sign error: No matching codesigning identity found: No codesigning identities (i.e. certificate and private key pairs) matching “Mac Developer” were found.

The workaround was to change to the Project Navigator, then change Build Settings > Code Signing to "Don't Code Sign". After that, I was able to build and run.

Not sure what the long-term solution is, but you might want to mention this in README.md for new users. =:)

**Comment by numist** [comment]
Good call. That plus the 10.9 SDK requirement reported in #21 are worth documenting, once it's verified.
