### ISSUE TITLE
Menu bar item

### ISSUE THREAD

**Issue by numist** [numist/Switch#37]
It's not ideal to show the preferences window based on a key combination that is somewhat non-standard and only valid when the interface is active. Switch should have a menu bar item that is enabled by default containing options to show preferences, quit, maybe other things.

It should be possible to disable the menu bar item from the preferences window, for people who prefer to keep things clean and don't already use [Bartender](http://www.macbartender.com) (by the way, you should be using Bartender!).

**Comment by ghost** [comment]
> It should be possible to disable the menu bar item from the preferences window

Since this issue is closed, was the above idea abandoned?
Many apps offer this and the common behaviour when the menu bar icon is hidden is to open the preferences window on every subsequent launch (every time the app is launched when the process is already running).

**Comment by numist** [comment]
It was closed by commit 6d26c25; you can enable or disable the status bar item at the bottom of the Advanced pane of the preferences window:

![screen shot 2016-04-17 at 18 24 21](https://cloud.githubusercontent.com/assets/544011/14591629/a4c2237e-04c9-11e6-981c-4b1eea96eee8.png)

**Comment by ghost** [comment]
OK, sorry. Just saw it was committed after the 0.0.8b release.

**Comment by numist** [comment]
This issue's milestone was [0.0.4 (α)](https://github.com/numist/Switch/issues?q=milestone%3A%220.0.4+%28α%29%22), it was fixed a year before [0.0.8 (β)](https://github.com/numist/Switch/issues?utf8=✓&q=milestone%3A%220.0.8+%28β%29%22+).

**Comment by ghost** [comment]
Sorry, didn't check the dates but in this case, something is wrong with my machine.
I'm on OS X 10.11.4 and 0.0.8 (β) and the window in your screenshot just shows the **Show interface on all screens** option, with the window resized accordingly to accommodate just that option, no whitespace beneath (I'll upload a screenshot later when I get home).

**Comment by numist** [comment]
Weird? I'm running [`develop`](https://github.com/numist/Switch/tree/develop) and it's definitely there, maybe it really was done separately/more recently and hasn't shipped out yet.

It has been a while and things seem pretty stable, maybe it's time to press another release. I'll scrub the current milestone after work tonight and see if anything critical is missing that would block a release.

**Comment by ghost** [comment]
Now, wait a minute there! =]

0.0.8 (β) ✈︎
@numist released this on **May 11, 2014** · [54 commits](https://github.com/numist/Switch/compare/0.0.8...develop) to develop since this release

Commits on **May 19, 2014**
@numist Checkboxes are NSButtons, not NSButtonCells 4aea097
@numist Try using some more const for constants. b76d7e4
@numist Refactor status item creation into its own method.  0328eb2
@numist Style dfa4ad9
**@numist Implement preference to hide status bar item. 0c524ba**
@numist     Ignore stuff in Pods/ 74caa98
@numist Merge pull request #97 from numist/numist/46 35ed320

**Comment by ghost** [comment]
I downloaded the [latest](https://github.com/numist/Switch/releases/download/0.0.8/Switch.zip).
![screencap-1461099010820](https://cloud.githubusercontent.com/assets/9649385/14655120/c963d3c0-0678-11e6-895e-5f4e3ac4e9b7.png)

**Comment by numist** [comment]
I guess I should press a new release then eh

**Comment by numist** [comment]
[0.0.10](https://github.com/numist/Switch/releases/tag/0.0.10) was released today, you can update from the preferences window :)
