### ISSUE TITLE
Make the flippedness of window frames less confusing by normalizing them at a lower level.

### ISSUE THREAD

**Issue by numist** [numist/Switch#89]
Only window frames coming from CG (and Accessibility) are actually flipped (per [the internet](http://www.krizka.net/2010/04/20/converting-between-kcgwindowbounds-and-nswindowframe/)) so it's probably a better abstraction to flip them internally and prevent this stuff from leaking out into high level implementation.

@robrix: How do you feel about implicitly flipping the frames returned from `HAXWindow` objects, since they're returning a CG worldview from a Cocoa-level interface?

**Comment by robrix** [comment]
Do it!

**Comment by numist** [comment]
Ok, I'm doing it!

**Comment by robrix** [comment]
:ok: :ok_hand: :ok_woman:
