### ISSUE TITLE
Window order with multiple screens

### ISSUE THREAD

**Issue by ghost** [numist/Switch#98]
At the moment, windows are not ordered by screen first. For example, say screen 1 has windows 1a, 1b and 1c, and screen 2 has windows 2a and 2b. In this case, cycling through the windows with ⌥⇥ may follow this order: 1a, 1b, 2a, 1c, 2b, and I find that the selection jumping from one screen to another is rather distracting.

I believe that Switch should either render a single list with all windows (like OS X does with ⌘⇥) or order the windows by screen first and then whichever order criteria it currently uses.

**Comment by numist** [comment]
At the moment Switch increments the selection based on MRU across all screens (for illustration, it describes the windows in your example as: 1a, 1b, 2c, 1d, 2e). This admittedly wasn't a designed experience so much as it was easier to implement and fit well with my own usage of Spaces/multiple desktops.

I can see how it's a bit jarring, so I'll experiment a bit with Space-prioritized incrementing and see how it feels—worst case there can be another checkbox in the preferences :)
